import type { Metadata } from "next";
import { Tilt_Warp } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/auth/components/AuthProvider";

const tiltWarp = Tilt_Warp({ subsets: ["latin"], weight:['400'] });

export const metadata: Metadata = {
  title: "AUTENTI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="es">
        <body className={tiltWarp.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
